"""Scaffolds a complete, self-contained episode workspace in one call:
episodes/{id}/episode.yaml, script.md, checklist.md, prompts/*.yaml, and the
assets/renders/exports subfolders — everything keyed by the same episode id.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from core.config import Settings, get_settings
from core.episode_repository import EpisodeRepository
from core.frontmatter import write_markdown
from core.models.episode import Episode
from core.models.prompt_record import PromptRecord
from core.utils import load_yaml_template, slugify

logger = logging.getLogger(__name__)

PROMPT_KINDS = ("image", "video", "voice", "thumbnail")
WORKSPACE_SUBFOLDERS = ("prompts", "assets", "renders", "exports")


@dataclass
class EpisodeScaffold:
    """Every path created for a new episode, all keyed by the same episode id."""

    episode: Episode
    workspace_dir: Path
    episode_path: Path
    script_path: Path
    checklist_path: Path
    prompt_paths: dict[str, Path] = field(default_factory=dict)


def _unique_id(title: str, repo: EpisodeRepository) -> str:
    base = slugify(title)
    candidate = base
    suffix = 2
    while repo.exists(candidate):
        candidate = f"{base}-{suffix}"
        suffix += 1
    return candidate


def _provider_for(settings: Settings, kind: str) -> str:
    """Thumbnails are generated by the image provider — there's no separate 'thumbnail' provider."""
    return settings.providers.image if kind == "thumbnail" else getattr(settings.providers, kind)


def create_episode(title: str, settings: Settings | None = None) -> EpisodeScaffold:
    """Create a new episode end to end: unique id, workspace folder, episode
    record, script/checklist markdown, and four draft prompt records — every
    path under episodes/{id}/.
    """
    settings = settings or get_settings()
    repo = EpisodeRepository(settings)

    episode_id = _unique_id(title, repo)
    workspace = repo.workspace_dir(episode_id)
    for subfolder in WORKSPACE_SUBFOLDERS:
        (workspace / subfolder).mkdir(parents=True, exist_ok=True)

    templates_dir = settings.paths.resolve("templates")

    script_path = workspace / "script.md"
    script_body = (templates_dir / "script_template.md").read_text(encoding="utf-8").format(title=title)
    write_markdown(
        script_path,
        {"id": f"{episode_id}-script", "episode_id": episode_id, "status": "draft", "version": 1},
        script_body,
    )

    checklist_path = workspace / "checklist.md"
    checklist_body = (templates_dir / "checklist_template.md").read_text(encoding="utf-8").format(title=title)
    write_markdown(
        checklist_path,
        {"id": f"{episode_id}-checklist", "episode_id": episode_id, "status": "draft", "version": 1},
        checklist_body,
    )

    prompt_paths: dict[str, Path] = {}
    for kind in PROMPT_KINDS:
        record = PromptRecord(
            id=f"{episode_id}-{kind}",
            episode_id=episode_id,
            provider=_provider_for(settings, kind),
            type=kind,
        )
        record_path = workspace / "prompts" / f"{kind}.yaml"
        with record_path.open("w", encoding="utf-8") as f:
            yaml.safe_dump(record.model_dump(mode="json"), f, sort_keys=False, allow_unicode=True)
        prompt_paths[kind] = record_path

    data = load_yaml_template(settings, "episode_template.yaml")
    data["id"] = episode_id
    data["title"] = title
    episode = Episode.model_validate(data)
    episode_path = repo.save(episode)

    logger.info("Scaffolded episode '%s' (%s) at %s", episode_id, title, workspace)

    return EpisodeScaffold(
        episode=episode,
        workspace_dir=workspace,
        episode_path=episode_path,
        script_path=script_path,
        checklist_path=checklist_path,
        prompt_paths=prompt_paths,
    )
